{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fib-calculator.fullname" . }}
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: spdevqa.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fib-calculator.fullname" . }}-client
            port:
              number: {{ .Values.client.service.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "fib-calculator.fullname" . }}-server
            port:
              number: {{ .Values.server.service.port }}
{{- end }}
