apiVersion: v1
kind: Service
metadata:
  name: {{ include "fib-calculator.fullname" . }}-server
  labels:
    {{- include "fib-calculator.labels" . | nindent 4 }}
    service: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fib-calculator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fib-calculator.fullname" . }}-client
  labels:
    {{- include "fib-calculator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fib-calculator.selectorLabels" . | nindent 4 }}
    service: client