# Default values for fib-calculator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

server:
  service:
    type: ClusterIP
    port: 5000
  image:
    repository: 289512055556.dkr.ecr.eu-central-1.amazonaws.com/nitaykd-assignment/server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.7"

worker:
  image:
    repository: 289512055556.dkr.ecr.eu-central-1.amazonaws.com/nitaykd-assignment/worker
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.7"

client:
  service:
    type: ClusterIP
    port: 3000
  image:
    repository: 289512055556.dkr.ecr.eu-central-1.amazonaws.com/nitaykd-assignment/client
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.7"


mysql:
  auth:
    username: mysqluser
    password: mysqlpassword
    rootPassword: mysqlrootpassword
    database: fib-calculator-database

redis:
  architecture: standalone
  auth:
    enabled: false

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

ingress:
  enabled: true
  host: spdevqa.com

resources: {}